config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tarefas.urls')),
    path('', include('usuarios.urls')),
]

tarefas/urls.py
from django.urls import path
from tarefas.views import index, task_detalhes, excluir_task, marcar_concluida, criar_task

urlpatterns = [
    path('', index, name='index'),
    path('detalhe/task_<int:id>/', task_detalhes, name='detalhe'),
    path('tarefa/<int:id>/excluir/', excluir_task, name='excluir_task'),
    path('tarefa//<int:id>/concluida/', marcar_concluida, name='marcar_concluida'),
    path('criar_task/', criar_task, name='criar_task')
]

usuarios/urls.py
from django.urls import path
from usuarios.views import cadastro, login, logout

urlpatterns = [
    path('cadastro', cadastro, name='cadastro'),
    path('login', login, name='login'),
    path('logout', logout, name='logout')
]

tarefas/models.py
from django.db import models
from django.contrib.auth.models import User

class Tarefa(models.Model):
    opcoes_prioridade = [
        ('Alta', 'Alta'),
        ('Média', 'Média'),
        ('Baixa', 'Baixa'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    titulo = models.CharField(max_length=50)

    descricao = models.TextField(max_length=70, blank=True)

    data = models.DateField()

    concluida = models.BooleanField(default=False)

    prioridade = models.CharField(max_length=30, choices=opcoes_prioridade)

    def __str__(self):
        return self.titulo

usuarios/models.py
from django.db import models

# Create your models here.

tarefas/forms.py
from django import forms

class TarefaForms(forms.Form):
    titulo_tarefa = forms.CharField(
        label='Título',
        required=True,
        max_length=100,
    )

    descricao_tarefa = forms.CharField(
        label='Descrição',
        max_length=150,
        widget=forms.Textarea(
            attrs={'rows':4}
        )
    )

    data = forms.DateField(
        label='Data',
        required=True,
        widget=forms.DateInput(
            attrs={'type':'date'}
        )
    )

    prioridade = forms.ChoiceField(
        label='Prioridade',
        choices=(
            ('Alta','Alta'),
            ('Média','Média'),
            ('Baixa','Baixa'),
        )
    )

usuarios/forms.py
from django import forms

class CadastroForm(forms.Form):
    nome_cadastro = forms.CharField(
        label='Nome',
        max_length=50,
        required=True,
    )

    email = forms.EmailField(
        label='Email',
        required=True,
        widget=forms.EmailInput
    )


    senha_1 = forms.CharField(
        label='Senha',
        max_length=50,
        required=True,
        widget=forms.PasswordInput(

        )
    )

    senha_2 = forms.CharField(
        label='Confirmar Senha',
        max_length=50,
        required=True,
        widget=forms.PasswordInput(

        )
    )

class LoginForm(forms.Form):
    nome_login = forms.CharField(
        label='Nome',
        max_length=50,
        required=True,
    )

    senha = forms.CharField(
        label='Senha',
        max_length=50,
        required=True,
        widget=forms.PasswordInput(

        )
    )

tarefas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from tarefas.forms import TarefaForms
from tarefas.models import Tarefa
from django.contrib import messages

def index(request):
    if not request.user.is_authenticated:
        messages.error(request, 'Faça login para continuar')
        return redirect('login')


    tarefas = Tarefa.objects.filter(usuario = request.user)
    return render(request, 'tarefas/index.html', {'tarefas': tarefas})

def task_detalhes(request, id):
    tarefas = get_object_or_404(Tarefa, id=id)
    
    return render(request, 'tarefas/task_detalhes.html', {'tarefas':tarefas})

def excluir_task(request, id):
    tarefa = get_object_or_404(Tarefa, id=id)
    tarefa.delete()

    return redirect('index')

def marcar_concluida(request, id):
    tarefa = get_object_or_404(Tarefa, id=id)
    tarefa.concluida = True
    tarefa.save()

    return redirect('detalhe', id = tarefa.id)
    
def criar_task(request):
    form = TarefaForms()
    if request.method == 'POST':
        form = TarefaForms(request.POST)

        if form.is_valid():
            titulo = form.cleaned_data['titulo_tarefa']
            descricao = form.cleaned_data['descricao_tarefa']
            data = form.cleaned_data['data']
            prioridade = form.cleaned_data['prioridade']

            tarefa = Tarefa.objects.create(
                usuario = request.user,
                titulo = titulo,
                descricao = descricao,
                data= data,
                prioridade = prioridade,
            )
            tarefa.save()
            
            return redirect('index')

    return render(request, 'tarefas/criar_task.html', {'form':form})

usuarios/views.py
from django.shortcuts import render, redirect
from usuarios.forms import CadastroForm, LoginForm
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib import messages

def cadastro(request):
    form = CadastroForm()

    if request.method == 'POST':
        form = CadastroForm(request.POST)

        if form.is_valid():
            if form['senha_1'].value() != form['senha_2'].value():
                return redirect('cadastro')
            
            nome = form['nome_cadastro'].value()
            email = form['email'].value()
            senha = form['senha_1'].value()

            usuario = User.objects.create_user(
                username=nome,
                email=email,
                password=senha
            )
            usuario.save()

            return redirect('login')

    return render(request, 'usuarios/cadastro.html', {'form':form})

def login(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            nome = form['nome_login'].value()
            senha = form['senha'].value()    

            usuario = auth.authenticate(
                request,
                username=nome,
                password=senha
            )    

            if usuario is not None:
                auth.login(request, usuario)
                return redirect('index')
            
            else:
                return redirect('login')

    return render(request, 'usuarios/login.html', {'form':form})

def logout(request):
    auth.logout(request)
    messages.success(request, 'Logout efetuado com sucesso!')
    return redirect('login')

templates/tarefas/criar_task.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nova Tarefa - Gerenciador de Tarefas</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <div class="container">
        <a href="/" class="back-link">
            <span class="back-arrow">←</span> Voltar
        </a>
        
        <div class="task-form-container">
            <div class="task-form-box">
                <h2>Nova Tarefa</h2>
                <form class="task-form" action="{% url 'criar_task' %}" method="POST">
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}
                    
                    <button type="submit" class="task-submit-button">Criar Tarefa</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/tarefas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Tarefas Hexagonal</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <div class="container">
        <nav class="auth-nav">
            {% if user.is_authenticated %}
            <a href="/logout" class="auth-link">Logout</a>
            {% endif %}
        </nav>
        
        <header>
            <h1>Lista de Tarefas</h1>
            <p class="subtitle">Organize suas atividades de forma hexagonal</p>
        </header>

        <div class="honeycomb">
            {% for tarefa in tarefas %}
            {% if tarefa.prioridade == 'Alta' %}
            <a href="detalhe/task_{{tarefa.id}}/" class="task-hex">
                <div class="task-content priority-high">
                    <h3>{{ tarefa.titulo }}</h3>
                    {% if not tarefa.concluida %}
                    <span class="tag-priority-high">Alta Prioridade</span>
                    {% else %}
                    <span class="tag-priority-high">Tarefa Concluída</span>
                    {% endif %}
                </div>
            </a>
            {% endif %}
            {% endfor %}

            {% for tarefa in tarefas %}
            {% if tarefa.prioridade == 'Média' %}
            <a href="detalhe/task_{{tarefa.id}}/" class="task-hex">
                <div class="task-content priority-medium">
                    <h3>{{ tarefa.titulo }}</h3>
                    {% if not tarefa.concluida %}
                    <span class="tag-priority-medium">Média Prioridade</span>
                    {% else %}
                    <span class="tag-priority-medium">Tarefa Concluída</span>
                    {% endif %}

                </div>
            </a>
            {% endif %}
            {% endfor %}
            
            {% for tarefa in tarefas %}
            {% if tarefa.prioridade == 'Baixa' %}
            <a href="detalhe/task_{{tarefa.id}}/" class="task-hex">
                <div class="task-content priority-low">
                    <h3>{{ tarefa.titulo }}</h3>
                    {% if not tarefa.concluida %}
                    <span class="tag-priority-low">Baixa Prioridade</span>
                    {% else %}
                    <span class="tag-priority-low">Tarefa Concluída</span>
                    {% endif %}
                </div>
            </a>
            {% endif %}
            {% endfor %}

            <a href="criar_task" class="task-hex add-task">
                <div class="task-content">
                    <span class="plus">+</span>
                    <p>Adicionar Tarefa</p>
                </div>
            </a>
        </div>
    </div>
</body>
</html>

templates/tarefas/task_detalhes.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes da Tarefa - Gerenciador de Tarefas</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <div class="container">
        <a href="/" class="back-link">
            <span class="back-arrow">←</span> Voltar
        </a>
    
        <div class="task-detail-container">
            <div class="task-detail {% if tarefas.prioridade == 'Alta' %}priority-high{% endif %}
            {% if tarefas.prioridade == 'Média' %}priority-medium{% endif %}
            {% if tarefas.prioridade == 'Baixa' %}priority-low{% endif %}">
                <div class="task-header">
                    <h2>{{ tarefas.titulo }}</h2>
                    <span class="{% if tarefas.prioridade == 'Alta' %}tag-priority-high{% endif %}
                    {% if tarefas.prioridade == 'Média' %}tag-priority-medium{% endif %}
                    {% if tarefas.prioridade == 'Baixa' %}tag-priority-low{% endif %}">{{ tarefas.get_prioridade_display }} Prioridade</span>
                </div>
                
                <div class="task-info">
                    <div class="info-group">
                        <h3>Descrição</h3>
                        {% if tarefas.descricao %}
                        <p>{{ tarefas.descricao }}</p>
                        {% else %}
                        <p>Nenhuma descrição fornecida</p>
                        {% endif %}
                    </div>
                    
                    <div class="info-group">
                        <h3>Data</h3>
                        <p>{{ tarefas.data|date:"d/m/Y" }}</p>
                    </div>
            
                    <div class="info-group">
                        <h3>Status</h3>
                        {% if not tarefas.concluida %}
                        <p>Em Andamento</p>
                        {% else %}
                        <p>Concluída</p>
                        {% endif %}
                    </div>
                </div>
                
                <div class="task-actions">
                    <!--Fazer a funcionalidade de editar a tarefa-->

                    <!---<button class="action-button edit">Editar</button>--->

                    <form action="{% url 'marcar_concluida' tarefas.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="action-button complete">
                            Marcar como Concluída
                        </button>
                    </form>
                    
                    <form action="{% url 'excluir_task' tarefas.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="action-button delete" onclick="return confirm('Tem certeza que deseja excluir esta tarefa?');">
                            Excluir
                        </button>
                    </form>
                    
                    
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/usuarios/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro - Gerenciador de Tarefas</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <div class="container">
        <a href="/" class="back-link">
            <span class="back-arrow">←</span> Voltar
        </a>
        
        <div class="auth-container">
            <div class="auth-box">
                <h2>Cadastro</h2>
                <form class="auth-form" action="{% url 'cadastro' %}" method="POST">
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}
                    <button type="submit" class="auth-button">Cadastrar</button>
                </form>
                <p class="auth-redirect">
                    Já tem uma conta? <a href="/login">Faça login</a>
                </p>
            </div>
        </div>
    </div>
</body>
</html>

templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Gerenciador de Tarefas</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <div class="container">
        <a href="/" class="back-link">
            <span class="back-arrow">←</span> Voltar
        </a>
        
        <div class="auth-container">
            <div class="auth-box">
                <h2>Login</h2>
                <form class="auth-form" method="POST" action="{% url 'login' %}" >
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}   
                    </div>
                    {% endfor %}
                    <button type="submit" class="auth-button">Entrar</button>
                </form>
                <p class="auth-redirect">
                    Não tem uma conta? <a href="/cadastro">Cadastre-se</a>
                </p>
            </div>
        </div>
    </div>
</body>
</html>